[project]
name = "pacman"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "fbendnan", email = "fatimazahrabendnane@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
pacman = "pacman:main"

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"
